dev/check-go: `go vet` should only look at `main.go`, certainly not untracked files

diff --git a/dev/check-go b/dev/check-go
--- a/dev/check-go
+++ b/dev/check-go
@@ -16,7 +16,7 @@ if [ -n "$unformatted" ]; then
     exit 1
 fi
 
-vetted="$(go vet ./... 2>&1)" || { echo "$vetted" >&2; echo "ERROR: go vet failed" >&2; exit 1; }
+vetted="$(go vet main.go 2>&1)" || { echo "$vetted" >&2; echo "ERROR: go vet failed" >&2; exit 1; }
 if [ -n "$vetted" ]; then
     echo "$vetted" >&2
     echo "ERROR: go vet had output" >&2
